# Generated by Django 3.1.7 on 2021-03-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsmodel',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
