# Generated by Django 3.1.7 on 2021-04-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_commentmodel_replycommentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=100)),
                ('package_speed', models.CharField(max_length=100)),
                ('package_category', models.CharField(choices=[('limited', 'limited'), ('unlimited', 'unlimited')], max_length=100)),
                ('validity', models.CharField(max_length=100)),
            ],
        ),
    ]
