# Generated by Django 3.1.7 on 2021-04-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='package_type',
            field=models.CharField(choices=[('Hostel', 'Hostel'), ('Home', 'Home'), ('Enterprise', 'Enterprise')], default='Home', max_length=100),
            preserve_default=False,
        ),
    ]
