# Generated by Django 3.1.7 on 2021-04-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_packages_package_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
